common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu_raw"
    # imu_topic:  "/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    # extrinsic_T: [ -0.017189, 0.015727, 0.106037]
    # extrinsic_R: [ -0.999887, -0.011619, -0.009487, 
    #                0.011486, -0.999838, 0.013885, 
    #                -0.009647, 0.013775, 0.99859]
    extrinsic_T: [ 0, 0, 0]
    extrinsic_R: [ 1, -0.011619, -0.009487, 
                   0.011486, 1, 0.013885, 
                   -0.009647, 0.013775, 1]

publish:     
    scan_publish_en:  true       # 'false' will close all the point cloud output
    dense_publish_en: ture       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # output the point cloud scans in IMU-body-frame